FROM ubuntu:latest

SHELL ["/bin/bash", "-c"]

RUN apt-get update && \
    apt-get install -y git

RUN git clone https://github.com/redis/redis.git && \
    cd redis

WORKDIR /redis

ENV DEBIAN_FRONTEND=noninteractive
RUN echo "8" > /etc/timezone && \
    apt-get install -y build-essential && \
    apt-get install -y wget && \
    apt-get install -y pkg-config && \
    apt-get install -y lsb-release && \
    apt-get install -y software-properties-common && \
    wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | apt-key add - && \
    apt-add-repository "deb http://build.openmodelica.org/apt $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get install -y openmodelica --no-install-recommends && \
    apt-get install -y tcl && \
    apt-get upgrade -y

RUN make && \
    make install

CMD ["redis-server"]
